# Generated by Django 4.2.24 on 2025-12-02 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0002_studentgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroupFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(choices=[('non_sequential', 'Не садити поруч (послідовні номери)')], max_length=50, verbose_name='Функція')),
                ('enabled', models.BooleanField(default=True, verbose_name='Увімкнено')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Параметри')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='roster.studentgroup')),
            ],
            options={
                'verbose_name': 'Налаштування групи',
                'verbose_name_plural': 'Налаштування груп',
                'unique_together': {('group', 'feature_key')},
            },
        ),
    ]
