# Generated by Django 4.2.24 on 2026-02-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('classroom_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID кабінету')),
                ('screenshots_enabled', models.BooleanField(default=True, verbose_name='Скріншоти увімкнені')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Кабінет',
                'verbose_name_plural': 'Кабінети',
            },
        ),
    ]
