# Generated by Django 4.2.24 on 2026-02-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0005_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace_number', models.IntegerField(unique=True, verbose_name='Номер робочого місця')),
                ('last_screenshot_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата останнього скріншоту')),
                ('last_screenshot_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ім'я файлу скріншоту")),
            ],
            options={
                'verbose_name': 'Робоче місце',
                'verbose_name_plural': 'Робочі місця',
            },
        ),
    ]
