# Generated by Django 4.2.24 on 2026-02-07 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0006_workplace'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkplaceScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot_filename', models.CharField(max_length=255, verbose_name="Ім'я файлу")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to=settings.AUTH_USER_MODEL)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='roster.workplace')),
            ],
            options={
                'verbose_name': 'Скріншот',
                'verbose_name_plural': 'Скріншоти',
                'ordering': ['-created_at'],
            },
        ),
    ]
