# Generated by Django 4.2.24 on 2026-02-07 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0007_workplacescreenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplace',
            name='last_screenshot_at',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='last_screenshot_filename',
        ),
    ]
