# Generated by Django 4.2.24 on 2026-02-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0008_remove_workplace_last_screenshot_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplacescreenshot',
            name='os_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Користувач OS'),
        ),
        migrations.AddField(
            model_name='workplacescreenshot',
            name='reported_workplace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Робоче місце (з запиту)'),
        ),
    ]
