# Generated by Django 4.2.24 on 2026-02-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0009_workplacescreenshot_os_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='screenshot_interval',
            field=models.IntegerField(default=60, verbose_name='Інтервал скріншотів (сек)'),
        ),
    ]
