# Generated by Django 4.2.24 on 2026-02-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0010_classroom_screenshot_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplacescreenshot',
            name='window_titles',
            field=models.JSONField(blank=True, default=list, verbose_name='Заголовки вікон'),
        ),
    ]
