# Generated by Django 4.2.24 on 2026-02-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0011_workplacescreenshot_window_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplacescreenshot',
            name='image_deleted',
            field=models.BooleanField(default=False, verbose_name='Зображення видалено'),
        ),
    ]
